name: detectron2-pipeline
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6.5
  - pip
  - numpy==1.17.2
  - tqdm=4.37.0
  - pytest==5.1.1
  - pytorch==1.4.0
  - torchvision==0.5.0
  - cython=0.29.14
  - munkres=1.0.12
  - pillow=6.2.1
  - pip:
    - opencv-contrib-python==4.0.0.21
    - git+https://github.com/facebookresearch/fvcore@9aab644f19d4cafa637d09c209392af56080b039
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
